// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blood_Donation_Project.Migrations
{
    [DbContext(typeof(BloodDbContext))]
    [Migration("20260324224936_BloodDonationProject")]
    partial class BloodDonationProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blood_Donation_Project.Models.Appointment", b =>
                {
                    b.Property<int>("Appointment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Appointment_ID"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Donor_ID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Appointment_ID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.BloodTypeTable", b =>
                {
                    b.Property<int>("BloodType_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodType_ID"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BloodType_ID");

                    b.ToTable("BloodTypeTable");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.DonatedBlood", b =>
                {
                    b.Property<int>("Donation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Donation_ID"));

                    b.Property<int>("Appointment_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Donor_ID")
                        .HasColumnType("int");

                    b.Property<int>("Nurse_ID")
                        .HasColumnType("int");

                    b.HasKey("Donation_ID");

                    b.ToTable("DonatedBlood");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.Donor", b =>
                {
                    b.Property<int>("Donor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Donor_ID"));

                    b.Property<int>("BloodType_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Donor_ID");

                    b.ToTable("Donor");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.FormAnswers", b =>
                {
                    b.Property<int>("Answers_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Answers_ID"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Form_ID")
                        .HasColumnType("int");

                    b.Property<int>("HealthQ_ID")
                        .HasColumnType("int");

                    b.HasKey("Answers_ID");

                    b.ToTable("FormAnswers");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.FormQuestions", b =>
                {
                    b.Property<int>("HealthQ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthQ_ID"));

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HealthQ_ID");

                    b.ToTable("FormQuestions");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.Inventory", b =>
                {
                    b.Property<int>("BloodBank_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodBank_ID"));

                    b.Property<int>("BloodType_ID")
                        .HasColumnType("int");

                    b.Property<int>("Donation_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("VolumeML")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BloodBank_ID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.MedicalForm", b =>
                {
                    b.Property<int>("Form_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Form_ID"));

                    b.Property<int>("Donor_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FormDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nurse_ID")
                        .HasColumnType("int");

                    b.HasKey("Form_ID");

                    b.ToTable("MedicalForm");
                });

            modelBuilder.Entity("Blood_Donation_Project.Models.Nurse", b =>
                {
                    b.Property<int>("Nurse_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nurse_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Nurse_ID");

                    b.ToTable("Nurse");
                });
#pragma warning restore 612, 618
        }
    }
}
